RuCl application 2-GSEE
lanl-ansi/qc-applications pull request #64
Opened 2024-12-10 19:17 UTC by zain2864

This PR focuses on adding application 2, Ground State Energy Estimation, to the RuCl notebook, which is in the MagLab chapter of the QCA Report. This includes, updating the notebook, adding a new script 'RuCl-GSEE-RE.py', and updating the PDF. This application is done using two algorithms, one being the Trotterized subprocess that we use from QCA for GSEE. Another algorithm is used from PyLIQTR, Qubitized Phase Estimation, which is being used to compare the RE's for GSEE. However, currently PyLIQTR currently does not have the ability to express the Hamiltonian correctly using their 'getInstance()' function, since there is no support for next-nearest and next-next-nearest neighbors.

2024-12-13 06:51 UTC, JonhasSC requested changes
Some changes and then should be good to merge

2024-12-13 06:51 UTC, JonhasSC commented on notebooks/RuClExample.ipynb
- Categorize misspelled in first paragraph of application 2
- discernible misspelled in first paragraph of application 2
- When describing the steps needed for constructing the hamiltonian, mention how because there are two different workflows, the trotterized subprocess QPE and the qubitized QPE, there are two ways you need to construct the hamiltonian as the two algorithms work with different types
- Wouldn't be able to incorporate DMRG into the notebook. Just make a note that to assume that the initial state has been prepared through DMRG
- I'm not a fan of pushing code that doesn't work because the package does not support the hamiltonian construction. I think it's best if you remove the work you did to construct the hamiltonian using pyLIQTR's model type and to remove the rest of the work using the qubitized QPE algorithm. However, do make a comment on how that workflow would look like if that was incorporated.
- Therefore, given the comments you wrote down on how the workflow looks like, do it with respect to the trotterized subprocess.

2024-12-13 06:51 UTC, JonhasSC commented on scripts/RuCl-GSEE-RE.py
> +import os
Looking at it now, a lot of the things here are just copied and pasted from the previous script. It maybe best to use the previous script, RuCl-RE.py and through flag usage, modify how it should perform. Maintaining two scripts where majority of the work is the same except for the algorithm usage is too hectic.

2024-12-13 20:44 UTC, zain2864 commented on scripts/RuCl-GSEE-RE.py
> +    nsteps = 1500000
This was added as cli argument, as well as algorithm mode, and evolution time.

2024-12-16 17:44 UTC, gsgrattan reviewed
For notebook comments see my comments for the script. Some minor stuff I'd like to addressed or commented on, see but otherwise this generally looks good

2024-12-17 00:56 UTC, zain2864 commented on notebooks/state_preparation_and_measurement.json
I actually had deleted this file already from this branch , because it seemed like an output file from another script/notebook. Is it needed?

2024-12-17 01:07 UTC, JonhasSC commented on notebooks/state_preparation_and_measurement.json
No, keep it removed

2024-12-17 01:12 UTC, JonhasSC commented on scripts/RuCl-GSEE-RE.py
> +        if distance == 1:
1. I agree with this sentiment. weight_j and weight_k can be assigned in the same conditional block.
2. I don't agree with this sentiment. The variable should only exist in that inner scope for that ith execution. This is actually safer code as we are only working with the variable as it exists, and does not allow any possibility to problematically reassign the variable.
3. I agree with this

2024-12-17 01:14 UTC, JonhasSC commented on scripts/RuCl-GSEE-RE.py
> +            g.add_edge(n, (r, c+2), label = 'Z2')
Can you clarify about this?

2024-12-17 01:15 UTC, JonhasSC commented on scripts/RuCl-GSEE-RE.py
> +    rucl_J1 = [-1.7, -0.5, -0.35, -0.5, -1.53, -1.53, 1.2, 0, -1.87, -0.3, -1.4, -0.2, -1.3, -4.6, -12, -3.5, -5.5, -0.95, 0.46]
I agree with this. Could be something like "test_input.csv" or something. It would allow the user to submit their own csv files too

2024-12-18 22:11 UTC, zain2864 commented on scripts/RuCl-GSEE-RE.py
> +        if distance == 1:
I added changes 1 and 3.

2024-12-18 22:12 UTC, zain2864 commented on scripts/RuCl-GSEE-RE.py
> +            g.add_edge(n, (r, c+2), label = 'Z2')
fixed this in most places I saw in both the notebook and script.

2024-12-18 22:12 UTC, zain2864 commented on scripts/RuCl-GSEE-RE.py
> +    for (n1,n2,d) in g.edges(data=True):
changed syntax to adhere to this.

2024-12-18 22:13 UTC, zain2864 commented on scripts/RuCl-GSEE-RE.py
> +def nx_rucl_terms(g, data_series):
done!

2024-12-18 22:13 UTC, zain2864 commented on scripts/RuCl-GSEE-RE.py
> +    rucl_J1 = [-1.7, -0.5, -0.35, -0.5, -1.53, -1.53, 1.2, 0, -1.87, -0.3, -1.4, -0.2, -1.3, -4.6, -12, -3.5, -5.5, -0.95, 0.46]
Added support for CSV file input, and new command line argument to be able to specify directory as well.

2024-12-18 22:16 UTC, zain2864 commented on scripts/RuCl-GSEE-RE.py
> +    rucl_J1 = [-1.7, -0.5, -0.35, -0.5, -1.53, -1.53, 1.2, 0, -1.87, -0.3, -1.4, -0.2, -1.3, -4.6, -12, -3.5, -5.5, -0.95, 0.46]
Just a note, I only did this for the script, since I believe for the notebook, it is helpful to see what they are.

2025-01-03 03:49 UTC, merged